apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kryo-mcp

resources:
  - namespace.yaml
  - kryo-mcp-configmap.yaml
  - kryo-mcp-deployment.yaml
  - kryo-mcp-service.yaml
  - demo-service-deployment.yaml
  - demo-service-service.yaml
