apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mission-control-mcp

resources:
  - namespace.yaml
  - mission-control-mcp-configmap.yaml
  - mission-control-mcp-deployment.yaml
  - mission-control-mcp-service.yaml
  - sample-service-deployment.yaml
  - sample-service-service.yaml
