apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: secrets-vault-sync
spec:
  hostAPI: https://infisical.replace-me.example/api
  syncConfig:
    resyncInterval: 1m
    instantUpdates: false
  authentication:
    kubernetesAuth:
      identityId: replace-with-infisical-machine-identity-id
      serviceAccountRef:
        name: mcp
        namespace: mcp
      secretsScope:
        projectId: replace-with-infisical-project-id
        envSlug: prod
        secretsPath: /kryo
        recursive: true
  managedKubeSecretReferences:
    - secretName: secrets-vault
      secretNamespace: mcp
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
